### ISSUE TITLE
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by QGB** [markmckinnon/Leveldb-py#1]
```

leveldb_viewer.exe
Traceback (most recent call last):
  File "leveldb_viewer.py", line 3, in <module>
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。
[8028] Failed to execute script leveldb_viewer

```

conda activate py365
conda install PyQt=5.12.3

## ok

**Comment by QGB** [comment]
```
C:\test\github\Leveldb-py\Code>python LevelDB_Viewer.py
Traceback (most recent call last):
  File "LevelDB_Viewer.py", line 10, in <module>
    import leveldb
ImportError: DLL load failed: 找不到指定的模块。


```

**Comment by QGB** [comment]
```
In [1234]: for n,u in py.enumerate(y):
      ...:     u='https://raw.githubusercontent.com'+u[18:]
      ...:     u=u.replace('/blob/','/')
      ...:     #if 'Rico' in u:break
      ...:     b=N.HTTP.get_byte(u,url_as_file=1,skip_if_exist=1,p=0)
      ...:     print(n,U.md5(b),'  ',U.sha256(b)[:8],b)
      ...: #    print(b.decode().splitlines()[0])
      ...:
0 9bccc9e266d3d8cedeebba04104dfd26    ffad9303 <273.000 KiB>C:/test/raw.githubusercontent.com/aman9dubey/underwriter/1541902229a188e1a3dbd6a0fd773e2ce0d1c96c/Text-Classification-master/py-leveldb-windows-build/leveldb.pyd
1 9bccc9e266d3d8cedeebba04104dfd26    ffad9303 <273.000 KiB>C:/test/raw.githubusercontent.com/markmckinnon/Leveldb-py/1a238ef472c4eb914aedfe01299e6cc8da83aa99/Binaries/leveldb_viewer/leveldb.pyd
2 bf3e6f33f7cd8da9c398870cf476f893    79fbbe77 <273.000 KiB>C:/test/raw.githubusercontent.com/markmckinnon/Leveldb-py/1a238ef472c4eb914aedfe01299e6cc8da83aa99/Code/leveldb.pyd
3 9bccc9e266d3d8cedeebba04104dfd26    ffad9303 <273.000 KiB>C:/test/raw.githubusercontent.com/tsunglinneil/toilet-business/d36052694a48fdc7c8c609e6072646617cc26649/doc/leveldb.pyd

```

**Comment by QGB** [comment]
```
(py365) C:\test\github\Leveldb-py\Binaries\leveldb_viewer>
(py365) C:\test\github\Leveldb-py\Binaries\leveldb_viewer>conda install pip=22.1.2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining pip=22.1.2:  25%|█████████████████▌                                                    | 1/4Examining python=3.6.5:  50%|███████ ███████████████████████                              |Examining python=3.6.5:  75%|█████████████████████████████████████████████ Examining @/win-64::__win==0=0:  75%|███████████████████████████████████████     Examining @/win-64::__win==0=0: 100%|█████████████████████████████████████████failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions


(py365) C:\test\github\Leveldb-py\Binaries\leveldb_viewer>conda install pip=20
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.13.0
  latest version: 4.14.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: C:\QGB\Anaconda3\envs\py365

  added / updated specs:
    - pip=20


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-20.0.2                 |           py36_1         1.9 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.9 MB

The following NEW packages will be INSTALLED:

  pip                conda-forge/win-64::pip-20.0.2-py36_1


Proceed ([y]/n)? n


CondaSystemExit: Exiting.


(py365) C:\test\github\Leveldb-py\Binaries\leveldb_viewer>conda install pip=21
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.13.0
  latest version: 4.14.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: C:\QGB\Anaconda3\envs\py365

  added / updated specs:
    - pip=21


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-21.2.4                 |     pyhd8ed1ab_0         1.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.1 MB

The following NEW packages will be INSTALLED:

  pip                conda-forge/noarch::pip-21.2.4-pyhd8ed1ab_0


Proceed ([y]/n)? n


CondaSystemExit: Exiting.


(py365) C:\test\github\Leveldb-py\Binaries\leveldb_viewer>conda install pip=22
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__win==0=0:  25%|████████████████████████                                                                        | 1/4 [Examining @/win-64::__win==0=0:  50%|████████████████████████████████████████████████                               Examining @/win-64::__archspec==1=x86_64:  50%|███████████████████████████████████████████                               Examining pip=22:  75%|██████████████████████████████████████████████████████████████████████ failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pip=22 -> python[version='>=3.10,<3.11.0a0|>=3.7|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0']

Your python: python=3.6.5

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions


```
